# -*- mode: ruby -*-
# vi: set ft=ruby :

# Part 2: single-node K3s cluster hosting three web apps
# routed by an Ingress based on the HTTP Host header.
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"

  config.vm.define "redei-maS" do |server|
    server.vm.hostname = "redei-maS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "redei-maS"
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/install.sh"
  end
end
