#!/bin/bash
# Installs K3s in server (control-plane) mode on this VM.
# Once k3s writes its node-token, we copy it to the shared /vagrant folder
# so the worker VM can read it and join the cluster.

set -euo pipefail

# Remove any stale token from a previous run
sudo rm -f /vagrant/token

# Install K3s in server mode
sudo curl -sfL https://get.k3s.io | sh -

# Wait until the token file is generated by K3s
until [ -f /var/lib/rancher/k3s/server/node-token ]; do
  sleep 2
done

# Share the token via the /vagrant mount so the worker can pick it up
sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/token
sudo chmod 644 /vagrant/token
