# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"

  config.vm.define "redei-maS" do |server|
    server.vm.hostname = "redei-maS"
    server.vm.network "private_network", ip: "192.168.56.112"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "redei-maS"
      vb.memory = "2048"
      vb.cpus = 2
    end
    server.vm.provision "shell", path: "scripts/install.sh"
  end
end